### ISSUE TITLE
this.Navigator error in index.js

### ISSUE THREAD

**Issue by guizmo** [Javascript-Ninja/react-navigation-mobx-helpers#1]
Hi there,
I am new to React native and Mobx so feel free to tell me if i'm not doing it right...

I installed your helper via yarn.
In myApp/node_modules/react-navigation-mobx-helpers/dist/ i get a compiled JS version of your TS file. 
While setting  new NavigationStore(RootNavigator) i got an error saying that "router" is undefined in line 12 of index.js.

To fix i manually moved "this.Navigator = Navigator;" from line 108 to the top...

Is there an error while compiling to JS or am i doing it wrong ?

![screen shot 2018-02-26 at 13 16 51](https://user-images.githubusercontent.com/699063/36650405-58203358-1af7-11e8-8d8e-f7caa7ad755d.png)

**Comment by el-psy-k** [comment]
@guizmo fixed https://github.com/Javascript-Ninja/react-navigation-mobx-helpers/commit/d7ba9724ff2e416ff5648c41596c1046118b7496
