### ISSUE TITLE
Can't use typescript with this library

### ISSUE THREAD

**Issue by tangkhaiphuong** [Javascript-Ninja/react-navigation-mobx-helpers#3]
When I use typescript with this library, the error occurs due type definition is not correct. So I workaround by changing from:

`import NavigationStore from 'react-navigation-mobx-helpers';`
to
`import NavigationStore from 'react-navigation-mobx-helpers/dist';`

I think when you combine the index.js & index.d.ts inside dist folder. So please add in package.json configure where type definition.

```
  "main": "index.js",
  "types": "index.d.ts",

```

**Comment by el-psy-k** [comment]
@tangkhaiphuong added da3c1d9
