### ISSUE TITLE
Beware of breaking changes of react-navigation 2.3.1

### ISSUE THREAD

**Issue by Dimous** [Javascript-Ninja/react-navigation-mobx-helpers#5]
https://github.com/react-navigation/react-navigation-redux-helpers/pull/37

**Comment by el-psy-k** [comment]
In the next major version of React Navigation, to be released in Fall 2018, react-navigation will no longer provide any information about how to integrate with third-party state management library.It will not be tested against or considered when making any design decisions for the library.
So I decided not to save the states of react-navigation,I want to use [this way](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html) to achieve custom navigation.

**Comment by NgKhanh** [comment]
If you not save state of react-navigation, It'll wrong state when user use back button on Android or swipe to back prev screen on iOS

**Comment by el-psy-k** [comment]
@NgKhanh Can you post example code and error log?
I'm using `react-navigation-mobx-helpers@2.0.0` + `react-navigation@2.5.5` , it works fine.
