### ISSUE TITLE
请问是否可以添加获取栈的路由层级的方法呢。

### ISSUE THREAD

**Issue by chuanzhang2018** [Javascript-Ninja/react-navigation-mobx-helpers#6]
目前2.0已经取消了addNavigationHelpers   mobx还可以实现获取栈的路由层级吗

**Comment by el-psy-k** [comment]
更多未暴露的api可以在rootNavigation.navigation下找到，因为`@types/react-navigation`缺少这些类型定义，使用typescript的时候可能会报错。
